/**
 * Bootstrap a brand-new @reponova/lang-* package end-to-end in a single guided
 * flow that mirrors what the Release workflow's publish matrix does for an
 * already-bootstrapped plugin:
 *
 *   1. npm publish --access public          (cwd: packages/<package-dir>)
 *   2. pnpm trust:configure --apply         (cwd: monorepo root)
 *   3. git tag <name>@<version> + push      (cwd: monorepo root)
 *   4. gh release create with CHANGELOG     (cwd: monorepo root)
 *
 * Every step is idempotent: rerunning the script after a partial success
 * skips whatever is already in place, so this is also the safe recovery
 * tool when one job of the publish matrix fails (for any reason — first
 * publish, network flake, etc.) and you want to converge the state by hand
 * before clicking "Re-run failed jobs" in Actions.
 *
 * Usage:
 *   pnpm bootstrap-plugin lang-typescript                # full flow, interactive
 *   pnpm bootstrap-plugin lang-typescript --yes          # skip confirmations
 *   pnpm bootstrap-plugin lang-typescript --skip-publish # only configure trust + tag + release
 *   pnpm bootstrap-plugin lang-typescript --skip-trust   # skip the trust step
 *   pnpm bootstrap-plugin lang-typescript --skip-tag     # skip git tag
 *   pnpm bootstrap-plugin lang-typescript --skip-release # skip GH Release
 */
import { readFile } from "node:fs/promises";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const SCOPE_PREFIX = "@reponova/lang-";

/**
 * Build the argv for `gh release create`. Pure function so tests can pin
 * down the exact flag set and prevent re-introducing the historical
 * `--notes "<inline markdown>"` shape that exploded under shell expansion
 * (zsh `nomatch` interpreting backticks / brackets in the changelog body).
 *
 * The release notes always come from a file (`--notes-file`) or are
 * generated by GitHub (`--generate-notes`). They are NEVER passed inline.
 *
 * Exported for unit tests.
 */
export function buildGhReleaseArgs(
  tag: string,
  source: { readonly notesFile: string } | { readonly generateNotes: true },
): readonly string[] {
  const base = ["release", "create", tag, "--title", tag];
  if ("generateNotes" in source) {
    return [...base, "--generate-notes"];
  }
  return [...base, "--notes-file", source.notesFile];
}

interface PackageJson {
  readonly name?: string;
  readonly version?: string;
  readonly private?: boolean;
}

interface CliOptions {
  readonly packageDir: string;
  readonly skipPublish: boolean;
  readonly skipTrust: boolean;
  readonly skipTag: boolean;
  readonly skipRelease: boolean;
  readonly yes: boolean;
}

function parseArgs(argv: readonly string[]): CliOptions {
  let packageDir: string | undefined;
  let skipPublish = false;
  let skipTrust = false;
  let skipTag = false;
  let skipRelease = false;
  let yes = false;

  for (const arg of argv) {
    if (arg === "--" || arg === "") continue;
    if (arg === "--skip-publish") {
      skipPublish = true;
    } else if (arg === "--skip-trust") {
      skipTrust = true;
    } else if (arg === "--skip-tag") {
      skipTag = true;
    } else if (arg === "--skip-release") {
      skipRelease = true;
    } else if (arg === "--yes" || arg === "-y") {
      yes = true;
    } else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else if (arg.startsWith("--")) {
      console.error(`[bootstrap-plugin] unknown argument: ${arg}`);
      printHelp();
      process.exit(2);
    } else if (!packageDir) {
      packageDir = arg;
    } else {
      console.error(`[bootstrap-plugin] unexpected positional argument: ${arg}`);
      printHelp();
      process.exit(2);
    }
  }

  if (!packageDir) {
    console.error(`[bootstrap-plugin] missing required argument: <package-dir>`);
    printHelp();
    process.exit(2);
  }

  return { packageDir, skipPublish, skipTrust, skipTag, skipRelease, yes };
}

function printHelp(): void {
  console.log(`Usage: bootstrap-plugin <package-dir> [options]

Bootstraps a brand-new @reponova/lang-* package end-to-end (npm publish +
trust + git tag + GitHub Release). Every step is idempotent so the script
is also the safe recovery tool when a publish-matrix job fails in CI.

Arguments:
  <package-dir>      Directory name under packages/ (e.g. lang-typescript).
                     The package.json must declare a name @reponova/lang-*
                     and must NOT be private.

Options:
  -y, --yes          Skip confirmation prompts.
  --skip-publish     Don't run npm publish.
  --skip-trust       Don't run pnpm trust:configure.
  --skip-tag         Don't create / push the git tag.
  --skip-release     Don't create the GitHub Release.
  -h, --help         Show this help.

Prerequisites:
  - npm CLI >= 11.10.0 (required by the trust subcommand)
  - You are logged in to npm: \`npm login\`
  - GitHub CLI (\`gh\`) installed and authenticated: \`gh auth login\`
  - When 2FA is requested on the first npm prompt, accept "skip 2FA for the
    next 5 minutes" so the trust step doesn't ask again.`);
}

function repoRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  // src/index.ts -> ../../../ = monorepo root
  return resolve(here, "..", "..", "..");
}

async function loadPackageJson(
  packageDir: string,
  root: string,
): Promise<{ pj: PackageJson; absPackageDir: string }> {
  const absPackageDir = resolve(root, "packages", packageDir);
  const pjPath = join(absPackageDir, "package.json");
  let raw: string;
  try {
    raw = await readFile(pjPath, "utf8");
  } catch (err) {
    throw new Error(`cannot read ${pjPath}: ${(err as Error).message}`);
  }
  let pj: PackageJson;
  try {
    pj = JSON.parse(raw) as PackageJson;
  } catch (err) {
    throw new Error(`${pjPath} is not valid JSON: ${(err as Error).message}`);
  }
  return { pj, absPackageDir };
}

function checkNpmVersion(): { ok: boolean; version: string } {
  const r = spawnSync("npm", ["--version"], { encoding: "utf8", shell: true });
  if (r.status !== 0) return { ok: false, version: "<unknown>" };
  const version = r.stdout.trim();
  const [maj, min] = version.split(".").map((n) => Number(n));
  if (typeof maj !== "number" || Number.isNaN(maj)) return { ok: false, version };
  if (maj > 11) return { ok: true, version };
  if (maj === 11 && (min ?? 0) >= 10) return { ok: true, version };
  return { ok: false, version };
}

function checkNpmAuth(): { ok: boolean; user: string } {
  const r = spawnSync("npm", ["whoami"], { encoding: "utf8", shell: true });
  if (r.status !== 0) return { ok: false, user: "" };
  return { ok: true, user: r.stdout.trim() };
}

function checkGhInstalled(): boolean {
  const r = spawnSync("gh", ["--version"], { encoding: "utf8", shell: true });
  return r.status === 0;
}

function checkGhAuth(): boolean {
  const r = spawnSync("gh", ["auth", "status"], {
    encoding: "utf8",
    shell: true,
  });
  return r.status === 0;
}

function checkAlreadyPublished(name: string, version: string): "yes" | "no" | "unknown" {
  const r = spawnSync("npm", ["view", `${name}@${version}`, "version"], {
    encoding: "utf8",
    shell: true,
  });
  if (r.status === 0 && r.stdout.trim() === version) return "yes";
  const stderr = r.stderr ?? "";
  if (stderr.includes("E404") || stderr.includes("404 Not Found")) return "no";
  return "unknown";
}

/** Returns true iff `refs/tags/<tag>` exists locally. */
function gitTagExistsLocal(tag: string, cwd: string): boolean {
  const r = spawnSync("git", ["rev-parse", "-q", "--verify", `refs/tags/${tag}`], {
    cwd,
    encoding: "utf8",
    shell: true,
  });
  return r.status === 0;
}

/** Returns true iff `refs/tags/<tag>` exists on the `origin` remote. */
function gitTagExistsRemote(tag: string, cwd: string): boolean {
  const r = spawnSync(
    "git",
    ["ls-remote", "--exit-code", "--tags", "origin", `refs/tags/${tag}`],
    { cwd, encoding: "utf8", shell: true },
  );
  return r.status === 0;
}

/** Returns true iff a GH Release with the given tag already exists. */
function ghReleaseExists(tag: string, cwd: string): boolean {
  const r = spawnSync("gh", ["release", "view", tag], {
    cwd,
    encoding: "utf8",
    shell: true,
  });
  return r.status === 0;
}

/**
 * Run the shared CHANGELOG section extractor and return its stdout, or
 * `null` if the section is not found / cannot be read.
 */
function extractChangelog(
  changelogPath: string,
  version: string,
  cwd: string,
): string | null {
  const script = resolve(cwd, ".github", "scripts", "extract-changelog.mjs");
  const r = spawnSync("node", [script, changelogPath, version], {
    cwd,
    encoding: "utf8",
    shell: true,
  });
  if (r.status === 0) return r.stdout;
  return null;
}

async function confirmPrompt(message: string, defaultYes: boolean): Promise<boolean> {
  const { createInterface } = await import("node:readline/promises");
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const yn = defaultYes ? "[Y/n]" : "[y/N]";
  try {
    const answer = await rl.question(`${message} ${yn} `);
    if (!answer.trim()) return defaultYes;
    return answer.trim().toLowerCase().startsWith("y");
  } finally {
    rl.close();
  }
}

async function main(): Promise<void> {
  const opts = parseArgs(process.argv.slice(2));
  const root = repoRoot();

  console.log(`[bootstrap-plugin] root:   ${root}`);
  console.log(`[bootstrap-plugin] target: packages/${opts.packageDir}`);
  console.log("");

  const { pj, absPackageDir } = await loadPackageJson(opts.packageDir, root);
  if (!pj.name) {
    throw new Error(`packages/${opts.packageDir}/package.json has no "name"`);
  }
  if (!pj.version) {
    throw new Error(`packages/${opts.packageDir}/package.json has no "version"`);
  }
  if (pj.private === true) {
    throw new Error(`packages/${opts.packageDir} is marked private — refusing to publish`);
  }
  if (!pj.name.startsWith(SCOPE_PREFIX)) {
    throw new Error(
      `packages/${opts.packageDir} package name "${pj.name}" does not match ${SCOPE_PREFIX}*`,
    );
  }

  const tag = `${pj.name}@${pj.version}`;
  console.log(`[bootstrap-plugin] package: ${tag}`);
  console.log("");

  const willPublish = !opts.skipPublish;
  const willTrust = !opts.skipTrust;
  const willTag = !opts.skipTag;
  const willRelease = !opts.skipRelease;

  // ---- Prereq checks --------------------------------------------------------
  if (willPublish || willTrust) {
    const v = checkNpmVersion();
    if (!v.ok) {
      console.error(
        `[bootstrap-plugin] npm >= 11.10.0 required (got ${v.version}). run: npm install -g npm@latest`,
      );
      process.exit(1);
    }
    const auth = checkNpmAuth();
    if (!auth.ok) {
      console.error(`[bootstrap-plugin] not authenticated. run: npm login`);
      process.exit(1);
    }
    console.log(`[bootstrap-plugin] npm version: ${v.version}`);
    console.log(`[bootstrap-plugin] npm user:    ${auth.user}`);
  }

  if (willRelease) {
    if (!checkGhInstalled()) {
      console.error(
        `[bootstrap-plugin] GitHub CLI (\`gh\`) is not installed. install from https://cli.github.com or rerun with --skip-release.`,
      );
      process.exit(1);
    }
    if (!checkGhAuth()) {
      console.error(
        `[bootstrap-plugin] \`gh\` is installed but not authenticated. run: gh auth login`,
      );
      process.exit(1);
    }
    console.log(`[bootstrap-plugin] gh:          authenticated`);
  }

  if (willPublish || willTrust || willRelease) console.log("");

  // ---- Step 1: npm publish --------------------------------------------------
  if (willPublish) {
    const status = checkAlreadyPublished(pj.name, pj.version);
    if (status === "yes") {
      console.log(
        `[bootstrap-plugin] ${tag} is already on the npm registry — skipping publish`,
      );
    } else {
      if (status === "unknown") {
        console.log(
          `[bootstrap-plugin] could not check npm registry for ${tag}; will attempt publish anyway`,
        );
      }
      if (!opts.yes) {
        const ok = await confirmPrompt(
          `[bootstrap-plugin] About to run \`npm publish --access public\` for ${tag}. Continue?`,
          true,
        );
        if (!ok) {
          console.log(`[bootstrap-plugin] aborted by user`);
          process.exit(1);
        }
      }
      console.log(
        `[bootstrap-plugin] $ npm publish --access public  (cwd: ${absPackageDir})`,
      );
      const r = spawnSync("npm", ["publish", "--access", "public"], {
        cwd: absPackageDir,
        stdio: "inherit",
        shell: true,
      });
      if (r.status !== 0) {
        console.error(`[bootstrap-plugin] npm publish failed (exit ${r.status})`);
        process.exit(1);
      }
      console.log(`[bootstrap-plugin] published ${tag}`);
    }
    console.log("");
  }

  // ---- Step 2: trust:configure ---------------------------------------------
  if (willTrust) {
    console.log(`[bootstrap-plugin] $ pnpm trust:configure --apply  (cwd: ${root})`);
    const r = spawnSync("pnpm", ["trust:configure", "--apply"], {
      cwd: root,
      stdio: "inherit",
      shell: true,
    });
    if (r.status !== 0) {
      console.error(`[bootstrap-plugin] trust:configure failed (exit ${r.status})`);
      process.exit(1);
    }
    console.log("");
  }

  // ---- Step 3: git tag ------------------------------------------------------
  if (willTag) {
    if (gitTagExistsLocal(tag, root)) {
      console.log(`[bootstrap-plugin] tag ${tag} already exists locally — skipping`);
    } else if (gitTagExistsRemote(tag, root)) {
      console.log(`[bootstrap-plugin] tag ${tag} already exists on origin — skipping`);
    } else {
      console.log(`[bootstrap-plugin] $ git tag ${tag}`);
      const tagResult = spawnSync("git", ["tag", tag], {
        cwd: root,
        stdio: "inherit",
        shell: true,
      });
      if (tagResult.status !== 0) {
        console.error(`[bootstrap-plugin] git tag failed (exit ${tagResult.status})`);
        process.exit(1);
      }
      console.log(`[bootstrap-plugin] $ git push origin refs/tags/${tag}`);
      const pushResult = spawnSync(
        "git",
        ["push", "origin", `refs/tags/${tag}`],
        { cwd: root, stdio: "inherit", shell: true },
      );
      if (pushResult.status !== 0) {
        console.error(
          `[bootstrap-plugin] git push tag failed (exit ${pushResult.status})`,
        );
        process.exit(1);
      }
    }
    console.log("");
  }

  // ---- Step 4: GitHub Release ----------------------------------------------
  if (willRelease) {
    if (ghReleaseExists(tag, root)) {
      console.log(`[bootstrap-plugin] GH Release ${tag} already exists — skipping`);
    } else {
      const changelogPath = `packages/${opts.packageDir}/CHANGELOG.md`;
      const notes = extractChangelog(changelogPath, pj.version, root);
      if (notes === null) {
        console.log(
          `[bootstrap-plugin] CHANGELOG section for ${pj.version} not found in ${changelogPath} — using --generate-notes`,
        );
        const args = buildGhReleaseArgs(tag, { generateNotes: true });
        console.log(`[bootstrap-plugin] $ gh ${args.join(" ")}`);
        const r = spawnSync("gh", [...args], {
          cwd: root,
          stdio: "inherit",
          shell: true,
        });
        if (r.status !== 0) {
          console.error(`[bootstrap-plugin] gh release create failed (exit ${r.status})`);
          process.exit(1);
        }
      } else {
        // Write the changelog chunk to a tmp file and pass it via
        // --notes-file. Inline --notes "<markdown>" was triggering shell
        // expansion of the changelog body (backticks, brackets, …) when
        // `shell: true` was set: e.g. zsh's `nomatch` interpreted markdown
        // like `### Minor Changes\n- [\`abc1234\`](url)` as a glob and
        // bailed out with `no matches found for \`Minor\``. A file path
        // is opaque to the shell, so the content survives verbatim. Same
        // approach as `.github/workflows/release.yml`.
        const notesDir = mkdtempSync(join(tmpdir(), "reponova-bootstrap-"));
        const notesFile = join(notesDir, "release-notes.md");
        writeFileSync(notesFile, notes, "utf8");
        try {
          const args = buildGhReleaseArgs(tag, { notesFile });
          console.log(
            `[bootstrap-plugin] $ gh ${args.slice(0, -1).join(" ")} <chunk from ${changelogPath}>`,
          );
          const r = spawnSync("gh", [...args], {
            cwd: root,
            stdio: "inherit",
            shell: true,
          });
          if (r.status !== 0) {
            console.error(
              `[bootstrap-plugin] gh release create failed (exit ${r.status})`,
            );
            process.exit(1);
          }
        } finally {
          rmSync(notesDir, { recursive: true, force: true });
        }
      }
    }
    console.log("");
  }

  console.log(
    `[bootstrap-plugin] done. ${pj.name} is ready for OIDC publishing from CI.`,
  );
  console.log(
    `[bootstrap-plugin] from the next version bump, no manual step is required.`,
  );
}

// Run main() only when this module is invoked as the entry point
// (i.e. `tsx src/index.ts ...`), NOT when imported by Vitest. Without
// this guard, importing pure helpers (e.g. `buildGhReleaseArgs`) from
// a test would also run the full CLI as a side effect.
const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] === __filename) {
  main().catch((err) => {
    console.error((err as Error).stack ?? String(err));
    process.exit(1);
  });
}
